In [2]:
import numpy as np

In [3]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
a = np.arange(0,21,1)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [4]:
#2.呈上題，將以上數列取出偶數。
b=a[a%2==0]
print(b)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [22]:
#3.呈1題，將數列取出3的倍數。
c=a[a%3==0]
print(c)

[ 3  6  9 12 15 18]


In [17]:
#4.[簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？
#list(a)只會轉換表層元素為list
a=np.arange(1,21,1).reshape(2,10)
print(a)
print('-------------')
print(list(a),'\n',type(list(a)[0]))
print('-------------')
#tolist()會把每層元素轉換成list
print(a.tolist(),'\n',type(a.tolist()[0]))

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
-------------
[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])] 
 <class 'numpy.ndarray'>
-------------
[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]] 
 <class 'list'>


In [21]:
#5.請試著在程式中印出以下三個 NdArray 的屬性？
#(屬性：ndim、shape、size、dtype、itemsize、length、type）
print(a)
print('ndim',':',a.ndim)#顯示維度大小
print('shape',':',a.shape)#顯示每個維度元素數量
print('size',':',a.size)#顯示矩陣內元素總數量
print('dtype',':',a.dtype)#顯示矩陣內元素資料型態
print('itemsize',':',a.itemsize)#顯示矩陣內每個元素所佔記憶體空間
print('length',':',len(a))#顯示最外層元素總數
print('type',':',type(a))#顯示矩陣的資料型態

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
ndim : 2
shape : (2, 10)
size : 20
dtype : int32
itemsize : 4
length : 2
type : <class 'numpy.ndarray'>


In [23]:
#6.如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
a=np.arange(1,21,1).reshape(2,10)
nums=np.arange(len(a))
b=[] # or b=list()
for i in nums:
    b.append(list(a[i]))#在list末尾增加更多元素
    
print(b)

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]
